---
name: Checks

#This is the trigger
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
#This defines a new job id "test-lint", 
#runs-on => is the runner the operating sys. for the job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#Define the first step of our job
#user => use the premade actions for some job
      - name: Checkout
        uses: actions/checkout@v2
#This step checkout => provided by github
#default code is not checkout
#we need to use the code for testing, thus checkout is needed
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
#Unit Test
      - name: Lint
        run: docker-compose run --rm app sh -c "run flake8"
#Flake8